name: Build Artifacts
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Something like this would be inside `build.yml`
  build_musl:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Build using Dockerfile
        id: build
        env:
          version: ${{ inputs.version }}
        run: |
          docker compose up --build --exit-code-from build-static
          version="$(./build/yt-dlp_static --version)"
          cat << EOF | tee -a "${GITHUB_OUTPUT}"
          version=${version}
          EOF

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-static-${{ github.job }}
          path: |
            ./build/yt-dlp*
          compression-level: 0

  # This would be handled automatically through current `release.yml`
  release:
    needs: [build_musl]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: build-*
          merge-multiple: true
      - name: Verification stuff
        run: |
          sha256sum artifact/yt-dlp_static
          sha512sum artifact/yt-dlp_static
          chmod +x artifact/yt-dlp_static
          artifact/yt-dlp_static -v || true
      - name: Publish release
        env:
          GH_TOKEN: ${{ github.token }}
          version: ${{ needs.build_musl.outputs.version }}
        run: |
          gh release create \
            --notes "***Experimental*** static musl libc yt-dlp build release" \
            --title "yt-dlp_static v${{ env.version }}" \
            --prerelease \
            v${{ env.version }} \
            artifact/*
