name: Build Artifacts
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_musl:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          # - armv7
          - aarch64

    steps:
      - uses: actions/checkout@v3
        with:
          repository: yt-dlp/yt-dlp
          path: ./repo

      - name: Virtualized Install, Prepare & Build
        uses: yt-dlp/run-on-arch-action@v2
        with:
          env: |
            GITHUB_WORKFLOW: build
          githubToken: ${{ github.token }}
          arch: ${{ matrix.architecture }}
          distro: alpine_latest
          dockerRunArgs: --volume "${PWD}/repo:/repo"
          install: |
            apk update
            apk add git python3 scons g++ patchelf binutils
            python3 -m venv .venv
            ./.venv/bin/activate
            python3 -m pip install -U pyinstaller staticx
            # TODO: requirements

          run: |
            cd /repo
            python3 -m pip install -U Pyinstaller -r requirements.txt
            python3 devscripts/make_lazy_extractors.py
            python3 pyinst.py --name yt-dlp_musl
            staticx dist/yt-dlp_musl dist/yt-dlp_musl_1
            mv -f dist/yt-dlp_musl dist/yt-dlp_musl

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            repo/dist/yt-dlp*
